language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
before_install:
 - sudo apt-get update
 - sudo apt-get install -y apt-transport-https
 - sudo apt-get update
 - sudo apt-get install -y dotnet-sdk-3.1
install:
 - pip install -r requirements.txt
 - pip install .
script: 
 - pytest tests/

